# Generated by Django 5.0.6 on 2024-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_prebodaform_alter_assistanceform_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.CharField(max_length=200)),
                ('wish', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='assistanceform',
            name='about_food',
            field=models.CharField(choices=[('1', 'Si, intolerancia al gluten'), ('2', 'Si, soy vegano'), ('3', 'si, soy vevetariano'), ('4', 'Otro, indicanoslo en el siguiente campo'), ('5', 'gracias a dios somos normales')], max_length=500),
        ),
        migrations.AlterField(
            model_name='prebodaform',
            name='mood',
            field=models.CharField(choices=[('1', 'la noche esta en pañales baby'), ('2', 'la ùltima y nos vamos'), ('3', 'da igual, aqui nadie nos conoce'), ('4', 'Si la vida te da limones, pide sal y tequila')], max_length=500),
        ),
    ]
