# Generated by Django 5.0.6 on 2024-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_wishform_alter_assistanceform_about_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistanceform',
            name='companions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prebodaform',
            name='companions',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
