# Generated by Django 5.0.6 on 2024-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanceform',
            name='companions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
