# Generated by Django 5.0.6 on 2024-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_assistanceform_companions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanceform',
            name='sugerencia',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
