# Generated by Django 5.0.6 on 2024-07-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_alter_assistanceform_sugerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanceform',
            name='companions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
