# Generated by Django 5.0.6 on 2024-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_alter_assistanceform_companions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanceform',
            name='about_food',
            field=models.CharField(choices=[('1', 'Si, intolerancia al gluten'), ('2', 'Si, soy vegano'), ('3', 'si, soy vevetariano'), ('4', 'Otro, indicanoslo en el siguiente campo'), ('5', 'No, ninguna')], max_length=500),
        ),
        migrations.AlterField(
            model_name='prebodaform',
            name='mood',
            field=models.CharField(choices=[('1', 'la noche esta en pañales baby'), ('2', 'la última y nos vamos'), ('3', 'da igual, aqui nadie nos conoce'), ('4', 'Si la vida te da limones, pide sal y tequila'), ('5', 'Es que mi abuela fuma y ...'), ('6', 'Un bidon de gasolina por favor !')], max_length=500),
        ),
    ]
