# Generated by Django 5.0.6 on 2024-07-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_alter_assistanceform_about_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanceform',
            name='about_food',
            field=models.CharField(choices=[('1', 'Si, intolerancia al gluten'), ('2', 'Si, soy vegano'), ('3', 'si, soy vevetariano'), ('4', 'Otro, indicanoslo en el siguiente campo'), ('5', 'No, ninguna')], default='5', max_length=500),
        ),
        migrations.AlterField(
            model_name='assistanceform',
            name='bus',
            field=models.CharField(choices=[('1', 'Si, necesitamos transporte'), ('2', 'No, usaremos el propio'), ('3', 'Si, solo ida'), ('4', 'Si, solo vuelta')], default='2', max_length=500),
        ),
        migrations.AlterField(
            model_name='prebodaform',
            name='assistance',
            field=models.CharField(choices=[('1', 'Si asistiré/asistiremos'), ('2', 'No, lamentablemente no puedo asistir')], max_length=500),
        ),
    ]
